// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Capacity.proto
// Protobuf Java Version: 4.29.0

package communication;

public final class CapacityOuterClass {
  private CapacityOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      CapacityOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CapacityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:communication.Capacity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 server1_status = 1;</code>
     * @return The server1Status.
     */
    int getServer1Status();

    /**
     * <code>int32 server2_status = 2;</code>
     * @return The server2Status.
     */
    int getServer2Status();

    /**
     * <code>int32 server3_status = 3;</code>
     * @return The server3Status.
     */
    int getServer3Status();

    /**
     * <code>int64 timestamp = 4;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code communication.Capacity}
   */
  public static final class Capacity extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:communication.Capacity)
      CapacityOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "",
        Capacity.class.getName());
    }
    // Use Capacity.newBuilder() to construct.
    private Capacity(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Capacity() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return communication.CapacityOuterClass.internal_static_communication_Capacity_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return communication.CapacityOuterClass.internal_static_communication_Capacity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              communication.CapacityOuterClass.Capacity.class, communication.CapacityOuterClass.Capacity.Builder.class);
    }

    public static final int SERVER1_STATUS_FIELD_NUMBER = 1;
    private int server1Status_ = 0;
    /**
     * <code>int32 server1_status = 1;</code>
     * @return The server1Status.
     */
    @java.lang.Override
    public int getServer1Status() {
      return server1Status_;
    }

    public static final int SERVER2_STATUS_FIELD_NUMBER = 2;
    private int server2Status_ = 0;
    /**
     * <code>int32 server2_status = 2;</code>
     * @return The server2Status.
     */
    @java.lang.Override
    public int getServer2Status() {
      return server2Status_;
    }

    public static final int SERVER3_STATUS_FIELD_NUMBER = 3;
    private int server3Status_ = 0;
    /**
     * <code>int32 server3_status = 3;</code>
     * @return The server3Status.
     */
    @java.lang.Override
    public int getServer3Status() {
      return server3Status_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_ = 0L;
    /**
     * <code>int64 timestamp = 4;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (server1Status_ != 0) {
        output.writeInt32(1, server1Status_);
      }
      if (server2Status_ != 0) {
        output.writeInt32(2, server2Status_);
      }
      if (server3Status_ != 0) {
        output.writeInt32(3, server3Status_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(4, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (server1Status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, server1Status_);
      }
      if (server2Status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, server2Status_);
      }
      if (server3Status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, server3Status_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof communication.CapacityOuterClass.Capacity)) {
        return super.equals(obj);
      }
      communication.CapacityOuterClass.Capacity other = (communication.CapacityOuterClass.Capacity) obj;

      if (getServer1Status()
          != other.getServer1Status()) return false;
      if (getServer2Status()
          != other.getServer2Status()) return false;
      if (getServer3Status()
          != other.getServer3Status()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVER1_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getServer1Status();
      hash = (37 * hash) + SERVER2_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getServer2Status();
      hash = (37 * hash) + SERVER3_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getServer3Status();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static communication.CapacityOuterClass.Capacity parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static communication.CapacityOuterClass.Capacity parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static communication.CapacityOuterClass.Capacity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static communication.CapacityOuterClass.Capacity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static communication.CapacityOuterClass.Capacity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static communication.CapacityOuterClass.Capacity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static communication.CapacityOuterClass.Capacity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static communication.CapacityOuterClass.Capacity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static communication.CapacityOuterClass.Capacity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static communication.CapacityOuterClass.Capacity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static communication.CapacityOuterClass.Capacity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static communication.CapacityOuterClass.Capacity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(communication.CapacityOuterClass.Capacity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code communication.Capacity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:communication.Capacity)
        communication.CapacityOuterClass.CapacityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return communication.CapacityOuterClass.internal_static_communication_Capacity_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return communication.CapacityOuterClass.internal_static_communication_Capacity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                communication.CapacityOuterClass.Capacity.class, communication.CapacityOuterClass.Capacity.Builder.class);
      }

      // Construct using communication.CapacityOuterClass.Capacity.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        server1Status_ = 0;
        server2Status_ = 0;
        server3Status_ = 0;
        timestamp_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return communication.CapacityOuterClass.internal_static_communication_Capacity_descriptor;
      }

      @java.lang.Override
      public communication.CapacityOuterClass.Capacity getDefaultInstanceForType() {
        return communication.CapacityOuterClass.Capacity.getDefaultInstance();
      }

      @java.lang.Override
      public communication.CapacityOuterClass.Capacity build() {
        communication.CapacityOuterClass.Capacity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public communication.CapacityOuterClass.Capacity buildPartial() {
        communication.CapacityOuterClass.Capacity result = new communication.CapacityOuterClass.Capacity(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(communication.CapacityOuterClass.Capacity result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.server1Status_ = server1Status_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.server2Status_ = server2Status_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.server3Status_ = server3Status_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.timestamp_ = timestamp_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof communication.CapacityOuterClass.Capacity) {
          return mergeFrom((communication.CapacityOuterClass.Capacity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(communication.CapacityOuterClass.Capacity other) {
        if (other == communication.CapacityOuterClass.Capacity.getDefaultInstance()) return this;
        if (other.getServer1Status() != 0) {
          setServer1Status(other.getServer1Status());
        }
        if (other.getServer2Status() != 0) {
          setServer2Status(other.getServer2Status());
        }
        if (other.getServer3Status() != 0) {
          setServer3Status(other.getServer3Status());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                server1Status_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                server2Status_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                server3Status_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int server1Status_ ;
      /**
       * <code>int32 server1_status = 1;</code>
       * @return The server1Status.
       */
      @java.lang.Override
      public int getServer1Status() {
        return server1Status_;
      }
      /**
       * <code>int32 server1_status = 1;</code>
       * @param value The server1Status to set.
       * @return This builder for chaining.
       */
      public Builder setServer1Status(int value) {

        server1Status_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 server1_status = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearServer1Status() {
        bitField0_ = (bitField0_ & ~0x00000001);
        server1Status_ = 0;
        onChanged();
        return this;
      }

      private int server2Status_ ;
      /**
       * <code>int32 server2_status = 2;</code>
       * @return The server2Status.
       */
      @java.lang.Override
      public int getServer2Status() {
        return server2Status_;
      }
      /**
       * <code>int32 server2_status = 2;</code>
       * @param value The server2Status to set.
       * @return This builder for chaining.
       */
      public Builder setServer2Status(int value) {

        server2Status_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 server2_status = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearServer2Status() {
        bitField0_ = (bitField0_ & ~0x00000002);
        server2Status_ = 0;
        onChanged();
        return this;
      }

      private int server3Status_ ;
      /**
       * <code>int32 server3_status = 3;</code>
       * @return The server3Status.
       */
      @java.lang.Override
      public int getServer3Status() {
        return server3Status_;
      }
      /**
       * <code>int32 server3_status = 3;</code>
       * @param value The server3Status to set.
       * @return This builder for chaining.
       */
      public Builder setServer3Status(int value) {

        server3Status_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 server3_status = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearServer3Status() {
        bitField0_ = (bitField0_ & ~0x00000004);
        server3Status_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 4;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 4;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:communication.Capacity)
    }

    // @@protoc_insertion_point(class_scope:communication.Capacity)
    private static final communication.CapacityOuterClass.Capacity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new communication.CapacityOuterClass.Capacity();
    }

    public static communication.CapacityOuterClass.Capacity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Capacity>
        PARSER = new com.google.protobuf.AbstractParser<Capacity>() {
      @java.lang.Override
      public Capacity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Capacity> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Capacity> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public communication.CapacityOuterClass.Capacity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_communication_Capacity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_communication_Capacity_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Capacity.proto\022\rcommunication\"e\n\010Capac" +
      "ity\022\026\n\016server1_status\030\001 \001(\005\022\026\n\016server2_s" +
      "tatus\030\002 \001(\005\022\026\n\016server3_status\030\003 \001(\005\022\021\n\tt" +
      "imestamp\030\004 \001(\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_communication_Capacity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_communication_Capacity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_communication_Capacity_descriptor,
        new java.lang.String[] { "Server1Status", "Server2Status", "Server3Status", "Timestamp", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
