// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Subscriber.proto
// Protobuf Java Version: 4.29.0

package communication;

public final class SubscriberOuterClass {
  private SubscriberOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      SubscriberOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code communication.DemandType}
   */
  public enum DemandType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Abone olma
     * </pre>
     *
     * <code>SUBS = 0;</code>
     */
    SUBS(0),
    /**
     * <pre>
     * Online
     * </pre>
     *
     * <code>ONLN = 1;</code>
     */
    ONLN(1),
    /**
     * <pre>
     * Offline
     * </pre>
     *
     * <code>OFFL = 2;</code>
     */
    OFFL(2),
    /**
     * <pre>
     * Abonelikten çıkma
     * </pre>
     *
     * <code>DEL = 3;</code>
     */
    DEL(3),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "",
        DemandType.class.getName());
    }
    /**
     * <pre>
     * Abone olma
     * </pre>
     *
     * <code>SUBS = 0;</code>
     */
    public static final int SUBS_VALUE = 0;
    /**
     * <pre>
     * Online
     * </pre>
     *
     * <code>ONLN = 1;</code>
     */
    public static final int ONLN_VALUE = 1;
    /**
     * <pre>
     * Offline
     * </pre>
     *
     * <code>OFFL = 2;</code>
     */
    public static final int OFFL_VALUE = 2;
    /**
     * <pre>
     * Abonelikten çıkma
     * </pre>
     *
     * <code>DEL = 3;</code>
     */
    public static final int DEL_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DemandType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DemandType forNumber(int value) {
      switch (value) {
        case 0: return SUBS;
        case 1: return ONLN;
        case 2: return OFFL;
        case 3: return DEL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DemandType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DemandType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DemandType>() {
            public DemandType findValueByNumber(int number) {
              return DemandType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return communication.SubscriberOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final DemandType[] VALUES = values();

    public static DemandType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DemandType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:communication.DemandType)
  }

  public interface SubscriberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:communication.Subscriber)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * SUBS, DEL, vb.
     * </pre>
     *
     * <code>.communication.DemandType demand = 1;</code>
     * @return The enum numeric value on the wire for demand.
     */
    int getDemandValue();
    /**
     * <pre>
     * SUBS, DEL, vb.
     * </pre>
     *
     * <code>.communication.DemandType demand = 1;</code>
     * @return The demand.
     */
    communication.SubscriberOuterClass.DemandType getDemand();

    /**
     * <pre>
     * Abone ID'si Ama şunu diyeyim uint32 olabilir çünkü sayı asla negatif olmayacak
     * </pre>
     *
     * <code>uint32 ID = 2;</code>
     * @return The iD.
     */
    int getID();

    /**
     * <pre>
     * İsim ve soyisim
     * </pre>
     *
     * <code>string name_surname = 3;</code>
     * @return The nameSurname.
     */
    java.lang.String getNameSurname();
    /**
     * <pre>
     * İsim ve soyisim
     * </pre>
     *
     * <code>string name_surname = 3;</code>
     * @return The bytes for nameSurname.
     */
    com.google.protobuf.ByteString
        getNameSurnameBytes();

    /**
     * <pre>
     * Başlangıç tarihi
     * </pre>
     *
     * <code>int64 start_date = 4;</code>
     * @return The startDate.
     */
    long getStartDate();

    /**
     * <pre>
     * Son erişim tarihi
     * </pre>
     *
     * <code>int64 last_accessed = 5;</code>
     * @return The lastAccessed.
     */
    long getLastAccessed();

    /**
     * <pre>
     * İlgi alanları
     * </pre>
     *
     * <code>repeated string interests = 6;</code>
     * @return A list containing the interests.
     */
    java.util.List<java.lang.String>
        getInterestsList();
    /**
     * <pre>
     * İlgi alanları
     * </pre>
     *
     * <code>repeated string interests = 6;</code>
     * @return The count of interests.
     */
    int getInterestsCount();
    /**
     * <pre>
     * İlgi alanları
     * </pre>
     *
     * <code>repeated string interests = 6;</code>
     * @param index The index of the element to return.
     * @return The interests at the given index.
     */
    java.lang.String getInterests(int index);
    /**
     * <pre>
     * İlgi alanları
     * </pre>
     *
     * <code>repeated string interests = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the interests at the given index.
     */
    com.google.protobuf.ByteString
        getInterestsBytes(int index);

    /**
     * <pre>
     * Çevrimiçi durumu
     * </pre>
     *
     * <code>bool isOnline = 7;</code>
     * @return The isOnline.
     */
    boolean getIsOnline();
  }
  /**
   * Protobuf type {@code communication.Subscriber}
   */
  public static final class Subscriber extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:communication.Subscriber)
      SubscriberOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "",
        Subscriber.class.getName());
    }
    // Use Subscriber.newBuilder() to construct.
    private Subscriber(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Subscriber() {
      demand_ = 0;
      nameSurname_ = "";
      interests_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return communication.SubscriberOuterClass.internal_static_communication_Subscriber_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return communication.SubscriberOuterClass.internal_static_communication_Subscriber_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              communication.SubscriberOuterClass.Subscriber.class, communication.SubscriberOuterClass.Subscriber.Builder.class);
    }

    public static final int DEMAND_FIELD_NUMBER = 1;
    private int demand_ = 0;
    /**
     * <pre>
     * SUBS, DEL, vb.
     * </pre>
     *
     * <code>.communication.DemandType demand = 1;</code>
     * @return The enum numeric value on the wire for demand.
     */
    @java.lang.Override public int getDemandValue() {
      return demand_;
    }
    /**
     * <pre>
     * SUBS, DEL, vb.
     * </pre>
     *
     * <code>.communication.DemandType demand = 1;</code>
     * @return The demand.
     */
    @java.lang.Override public communication.SubscriberOuterClass.DemandType getDemand() {
      communication.SubscriberOuterClass.DemandType result = communication.SubscriberOuterClass.DemandType.forNumber(demand_);
      return result == null ? communication.SubscriberOuterClass.DemandType.UNRECOGNIZED : result;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int iD_ = 0;
    /**
     * <pre>
     * Abone ID'si Ama şunu diyeyim uint32 olabilir çünkü sayı asla negatif olmayacak
     * </pre>
     *
     * <code>uint32 ID = 2;</code>
     * @return The iD.
     */
    @java.lang.Override
    public int getID() {
      return iD_;
    }

    public static final int NAME_SURNAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nameSurname_ = "";
    /**
     * <pre>
     * İsim ve soyisim
     * </pre>
     *
     * <code>string name_surname = 3;</code>
     * @return The nameSurname.
     */
    @java.lang.Override
    public java.lang.String getNameSurname() {
      java.lang.Object ref = nameSurname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nameSurname_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * İsim ve soyisim
     * </pre>
     *
     * <code>string name_surname = 3;</code>
     * @return The bytes for nameSurname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameSurnameBytes() {
      java.lang.Object ref = nameSurname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nameSurname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int START_DATE_FIELD_NUMBER = 4;
    private long startDate_ = 0L;
    /**
     * <pre>
     * Başlangıç tarihi
     * </pre>
     *
     * <code>int64 start_date = 4;</code>
     * @return The startDate.
     */
    @java.lang.Override
    public long getStartDate() {
      return startDate_;
    }

    public static final int LAST_ACCESSED_FIELD_NUMBER = 5;
    private long lastAccessed_ = 0L;
    /**
     * <pre>
     * Son erişim tarihi
     * </pre>
     *
     * <code>int64 last_accessed = 5;</code>
     * @return The lastAccessed.
     */
    @java.lang.Override
    public long getLastAccessed() {
      return lastAccessed_;
    }

    public static final int INTERESTS_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList interests_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <pre>
     * İlgi alanları
     * </pre>
     *
     * <code>repeated string interests = 6;</code>
     * @return A list containing the interests.
     */
    public com.google.protobuf.ProtocolStringList
        getInterestsList() {
      return interests_;
    }
    /**
     * <pre>
     * İlgi alanları
     * </pre>
     *
     * <code>repeated string interests = 6;</code>
     * @return The count of interests.
     */
    public int getInterestsCount() {
      return interests_.size();
    }
    /**
     * <pre>
     * İlgi alanları
     * </pre>
     *
     * <code>repeated string interests = 6;</code>
     * @param index The index of the element to return.
     * @return The interests at the given index.
     */
    public java.lang.String getInterests(int index) {
      return interests_.get(index);
    }
    /**
     * <pre>
     * İlgi alanları
     * </pre>
     *
     * <code>repeated string interests = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the interests at the given index.
     */
    public com.google.protobuf.ByteString
        getInterestsBytes(int index) {
      return interests_.getByteString(index);
    }

    public static final int ISONLINE_FIELD_NUMBER = 7;
    private boolean isOnline_ = false;
    /**
     * <pre>
     * Çevrimiçi durumu
     * </pre>
     *
     * <code>bool isOnline = 7;</code>
     * @return The isOnline.
     */
    @java.lang.Override
    public boolean getIsOnline() {
      return isOnline_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (demand_ != communication.SubscriberOuterClass.DemandType.SUBS.getNumber()) {
        output.writeEnum(1, demand_);
      }
      if (iD_ != 0) {
        output.writeUInt32(2, iD_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nameSurname_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, nameSurname_);
      }
      if (startDate_ != 0L) {
        output.writeInt64(4, startDate_);
      }
      if (lastAccessed_ != 0L) {
        output.writeInt64(5, lastAccessed_);
      }
      for (int i = 0; i < interests_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, interests_.getRaw(i));
      }
      if (isOnline_ != false) {
        output.writeBool(7, isOnline_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (demand_ != communication.SubscriberOuterClass.DemandType.SUBS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, demand_);
      }
      if (iD_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, iD_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nameSurname_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, nameSurname_);
      }
      if (startDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, startDate_);
      }
      if (lastAccessed_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, lastAccessed_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < interests_.size(); i++) {
          dataSize += computeStringSizeNoTag(interests_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getInterestsList().size();
      }
      if (isOnline_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, isOnline_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof communication.SubscriberOuterClass.Subscriber)) {
        return super.equals(obj);
      }
      communication.SubscriberOuterClass.Subscriber other = (communication.SubscriberOuterClass.Subscriber) obj;

      if (demand_ != other.demand_) return false;
      if (getID()
          != other.getID()) return false;
      if (!getNameSurname()
          .equals(other.getNameSurname())) return false;
      if (getStartDate()
          != other.getStartDate()) return false;
      if (getLastAccessed()
          != other.getLastAccessed()) return false;
      if (!getInterestsList()
          .equals(other.getInterestsList())) return false;
      if (getIsOnline()
          != other.getIsOnline()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEMAND_FIELD_NUMBER;
      hash = (53 * hash) + demand_;
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getID();
      hash = (37 * hash) + NAME_SURNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNameSurname().hashCode();
      hash = (37 * hash) + START_DATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStartDate());
      hash = (37 * hash) + LAST_ACCESSED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastAccessed());
      if (getInterestsCount() > 0) {
        hash = (37 * hash) + INTERESTS_FIELD_NUMBER;
        hash = (53 * hash) + getInterestsList().hashCode();
      }
      hash = (37 * hash) + ISONLINE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsOnline());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static communication.SubscriberOuterClass.Subscriber parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static communication.SubscriberOuterClass.Subscriber parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static communication.SubscriberOuterClass.Subscriber parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static communication.SubscriberOuterClass.Subscriber parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static communication.SubscriberOuterClass.Subscriber parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static communication.SubscriberOuterClass.Subscriber parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static communication.SubscriberOuterClass.Subscriber parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static communication.SubscriberOuterClass.Subscriber parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static communication.SubscriberOuterClass.Subscriber parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static communication.SubscriberOuterClass.Subscriber parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static communication.SubscriberOuterClass.Subscriber parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static communication.SubscriberOuterClass.Subscriber parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(communication.SubscriberOuterClass.Subscriber prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code communication.Subscriber}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:communication.Subscriber)
        communication.SubscriberOuterClass.SubscriberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return communication.SubscriberOuterClass.internal_static_communication_Subscriber_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return communication.SubscriberOuterClass.internal_static_communication_Subscriber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                communication.SubscriberOuterClass.Subscriber.class, communication.SubscriberOuterClass.Subscriber.Builder.class);
      }

      // Construct using communication.SubscriberOuterClass.Subscriber.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        demand_ = 0;
        iD_ = 0;
        nameSurname_ = "";
        startDate_ = 0L;
        lastAccessed_ = 0L;
        interests_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        isOnline_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return communication.SubscriberOuterClass.internal_static_communication_Subscriber_descriptor;
      }

      @java.lang.Override
      public communication.SubscriberOuterClass.Subscriber getDefaultInstanceForType() {
        return communication.SubscriberOuterClass.Subscriber.getDefaultInstance();
      }

      @java.lang.Override
      public communication.SubscriberOuterClass.Subscriber build() {
        communication.SubscriberOuterClass.Subscriber result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public communication.SubscriberOuterClass.Subscriber buildPartial() {
        communication.SubscriberOuterClass.Subscriber result = new communication.SubscriberOuterClass.Subscriber(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(communication.SubscriberOuterClass.Subscriber result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.demand_ = demand_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.iD_ = iD_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.nameSurname_ = nameSurname_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.startDate_ = startDate_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.lastAccessed_ = lastAccessed_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          interests_.makeImmutable();
          result.interests_ = interests_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.isOnline_ = isOnline_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof communication.SubscriberOuterClass.Subscriber) {
          return mergeFrom((communication.SubscriberOuterClass.Subscriber)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(communication.SubscriberOuterClass.Subscriber other) {
        if (other == communication.SubscriberOuterClass.Subscriber.getDefaultInstance()) return this;
        if (other.demand_ != 0) {
          setDemandValue(other.getDemandValue());
        }
        if (other.getID() != 0) {
          setID(other.getID());
        }
        if (!other.getNameSurname().isEmpty()) {
          nameSurname_ = other.nameSurname_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getStartDate() != 0L) {
          setStartDate(other.getStartDate());
        }
        if (other.getLastAccessed() != 0L) {
          setLastAccessed(other.getLastAccessed());
        }
        if (!other.interests_.isEmpty()) {
          if (interests_.isEmpty()) {
            interests_ = other.interests_;
            bitField0_ |= 0x00000020;
          } else {
            ensureInterestsIsMutable();
            interests_.addAll(other.interests_);
          }
          onChanged();
        }
        if (other.getIsOnline() != false) {
          setIsOnline(other.getIsOnline());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                demand_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                iD_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                nameSurname_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                startDate_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                lastAccessed_ = input.readInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureInterestsIsMutable();
                interests_.add(s);
                break;
              } // case 50
              case 56: {
                isOnline_ = input.readBool();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int demand_ = 0;
      /**
       * <pre>
       * SUBS, DEL, vb.
       * </pre>
       *
       * <code>.communication.DemandType demand = 1;</code>
       * @return The enum numeric value on the wire for demand.
       */
      @java.lang.Override public int getDemandValue() {
        return demand_;
      }
      /**
       * <pre>
       * SUBS, DEL, vb.
       * </pre>
       *
       * <code>.communication.DemandType demand = 1;</code>
       * @param value The enum numeric value on the wire for demand to set.
       * @return This builder for chaining.
       */
      public Builder setDemandValue(int value) {
        demand_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * SUBS, DEL, vb.
       * </pre>
       *
       * <code>.communication.DemandType demand = 1;</code>
       * @return The demand.
       */
      @java.lang.Override
      public communication.SubscriberOuterClass.DemandType getDemand() {
        communication.SubscriberOuterClass.DemandType result = communication.SubscriberOuterClass.DemandType.forNumber(demand_);
        return result == null ? communication.SubscriberOuterClass.DemandType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * SUBS, DEL, vb.
       * </pre>
       *
       * <code>.communication.DemandType demand = 1;</code>
       * @param value The demand to set.
       * @return This builder for chaining.
       */
      public Builder setDemand(communication.SubscriberOuterClass.DemandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        demand_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * SUBS, DEL, vb.
       * </pre>
       *
       * <code>.communication.DemandType demand = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDemand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        demand_ = 0;
        onChanged();
        return this;
      }

      private int iD_ ;
      /**
       * <pre>
       * Abone ID'si Ama şunu diyeyim uint32 olabilir çünkü sayı asla negatif olmayacak
       * </pre>
       *
       * <code>uint32 ID = 2;</code>
       * @return The iD.
       */
      @java.lang.Override
      public int getID() {
        return iD_;
      }
      /**
       * <pre>
       * Abone ID'si Ama şunu diyeyim uint32 olabilir çünkü sayı asla negatif olmayacak
       * </pre>
       *
       * <code>uint32 ID = 2;</code>
       * @param value The iD to set.
       * @return This builder for chaining.
       */
      public Builder setID(int value) {

        iD_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Abone ID'si Ama şunu diyeyim uint32 olabilir çünkü sayı asla negatif olmayacak
       * </pre>
       *
       * <code>uint32 ID = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        iD_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object nameSurname_ = "";
      /**
       * <pre>
       * İsim ve soyisim
       * </pre>
       *
       * <code>string name_surname = 3;</code>
       * @return The nameSurname.
       */
      public java.lang.String getNameSurname() {
        java.lang.Object ref = nameSurname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nameSurname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * İsim ve soyisim
       * </pre>
       *
       * <code>string name_surname = 3;</code>
       * @return The bytes for nameSurname.
       */
      public com.google.protobuf.ByteString
          getNameSurnameBytes() {
        java.lang.Object ref = nameSurname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nameSurname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * İsim ve soyisim
       * </pre>
       *
       * <code>string name_surname = 3;</code>
       * @param value The nameSurname to set.
       * @return This builder for chaining.
       */
      public Builder setNameSurname(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nameSurname_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * İsim ve soyisim
       * </pre>
       *
       * <code>string name_surname = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNameSurname() {
        nameSurname_ = getDefaultInstance().getNameSurname();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * İsim ve soyisim
       * </pre>
       *
       * <code>string name_surname = 3;</code>
       * @param value The bytes for nameSurname to set.
       * @return This builder for chaining.
       */
      public Builder setNameSurnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nameSurname_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private long startDate_ ;
      /**
       * <pre>
       * Başlangıç tarihi
       * </pre>
       *
       * <code>int64 start_date = 4;</code>
       * @return The startDate.
       */
      @java.lang.Override
      public long getStartDate() {
        return startDate_;
      }
      /**
       * <pre>
       * Başlangıç tarihi
       * </pre>
       *
       * <code>int64 start_date = 4;</code>
       * @param value The startDate to set.
       * @return This builder for chaining.
       */
      public Builder setStartDate(long value) {

        startDate_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Başlangıç tarihi
       * </pre>
       *
       * <code>int64 start_date = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartDate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        startDate_ = 0L;
        onChanged();
        return this;
      }

      private long lastAccessed_ ;
      /**
       * <pre>
       * Son erişim tarihi
       * </pre>
       *
       * <code>int64 last_accessed = 5;</code>
       * @return The lastAccessed.
       */
      @java.lang.Override
      public long getLastAccessed() {
        return lastAccessed_;
      }
      /**
       * <pre>
       * Son erişim tarihi
       * </pre>
       *
       * <code>int64 last_accessed = 5;</code>
       * @param value The lastAccessed to set.
       * @return This builder for chaining.
       */
      public Builder setLastAccessed(long value) {

        lastAccessed_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Son erişim tarihi
       * </pre>
       *
       * <code>int64 last_accessed = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastAccessed() {
        bitField0_ = (bitField0_ & ~0x00000010);
        lastAccessed_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList interests_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureInterestsIsMutable() {
        if (!interests_.isModifiable()) {
          interests_ = new com.google.protobuf.LazyStringArrayList(interests_);
        }
        bitField0_ |= 0x00000020;
      }
      /**
       * <pre>
       * İlgi alanları
       * </pre>
       *
       * <code>repeated string interests = 6;</code>
       * @return A list containing the interests.
       */
      public com.google.protobuf.ProtocolStringList
          getInterestsList() {
        interests_.makeImmutable();
        return interests_;
      }
      /**
       * <pre>
       * İlgi alanları
       * </pre>
       *
       * <code>repeated string interests = 6;</code>
       * @return The count of interests.
       */
      public int getInterestsCount() {
        return interests_.size();
      }
      /**
       * <pre>
       * İlgi alanları
       * </pre>
       *
       * <code>repeated string interests = 6;</code>
       * @param index The index of the element to return.
       * @return The interests at the given index.
       */
      public java.lang.String getInterests(int index) {
        return interests_.get(index);
      }
      /**
       * <pre>
       * İlgi alanları
       * </pre>
       *
       * <code>repeated string interests = 6;</code>
       * @param index The index of the value to return.
       * @return The bytes of the interests at the given index.
       */
      public com.google.protobuf.ByteString
          getInterestsBytes(int index) {
        return interests_.getByteString(index);
      }
      /**
       * <pre>
       * İlgi alanları
       * </pre>
       *
       * <code>repeated string interests = 6;</code>
       * @param index The index to set the value at.
       * @param value The interests to set.
       * @return This builder for chaining.
       */
      public Builder setInterests(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureInterestsIsMutable();
        interests_.set(index, value);
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * İlgi alanları
       * </pre>
       *
       * <code>repeated string interests = 6;</code>
       * @param value The interests to add.
       * @return This builder for chaining.
       */
      public Builder addInterests(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureInterestsIsMutable();
        interests_.add(value);
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * İlgi alanları
       * </pre>
       *
       * <code>repeated string interests = 6;</code>
       * @param values The interests to add.
       * @return This builder for chaining.
       */
      public Builder addAllInterests(
          java.lang.Iterable<java.lang.String> values) {
        ensureInterestsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, interests_);
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * İlgi alanları
       * </pre>
       *
       * <code>repeated string interests = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearInterests() {
        interests_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * İlgi alanları
       * </pre>
       *
       * <code>repeated string interests = 6;</code>
       * @param value The bytes of the interests to add.
       * @return This builder for chaining.
       */
      public Builder addInterestsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureInterestsIsMutable();
        interests_.add(value);
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private boolean isOnline_ ;
      /**
       * <pre>
       * Çevrimiçi durumu
       * </pre>
       *
       * <code>bool isOnline = 7;</code>
       * @return The isOnline.
       */
      @java.lang.Override
      public boolean getIsOnline() {
        return isOnline_;
      }
      /**
       * <pre>
       * Çevrimiçi durumu
       * </pre>
       *
       * <code>bool isOnline = 7;</code>
       * @param value The isOnline to set.
       * @return This builder for chaining.
       */
      public Builder setIsOnline(boolean value) {

        isOnline_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Çevrimiçi durumu
       * </pre>
       *
       * <code>bool isOnline = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsOnline() {
        bitField0_ = (bitField0_ & ~0x00000040);
        isOnline_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:communication.Subscriber)
    }

    // @@protoc_insertion_point(class_scope:communication.Subscriber)
    private static final communication.SubscriberOuterClass.Subscriber DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new communication.SubscriberOuterClass.Subscriber();
    }

    public static communication.SubscriberOuterClass.Subscriber getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Subscriber>
        PARSER = new com.google.protobuf.AbstractParser<Subscriber>() {
      @java.lang.Override
      public Subscriber parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Subscriber> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Subscriber> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public communication.SubscriberOuterClass.Subscriber getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_communication_Subscriber_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_communication_Subscriber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Subscriber.proto\022\rcommunication\"\251\001\n\nSu" +
      "bscriber\022)\n\006demand\030\001 \001(\0162\031.communication" +
      ".DemandType\022\n\n\002ID\030\002 \001(\r\022\024\n\014name_surname\030" +
      "\003 \001(\t\022\022\n\nstart_date\030\004 \001(\003\022\025\n\rlast_access" +
      "ed\030\005 \001(\003\022\021\n\tinterests\030\006 \003(\t\022\020\n\010isOnline\030" +
      "\007 \001(\010*3\n\nDemandType\022\010\n\004SUBS\020\000\022\010\n\004ONLN\020\001\022" +
      "\010\n\004OFFL\020\002\022\007\n\003DEL\020\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_communication_Subscriber_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_communication_Subscriber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_communication_Subscriber_descriptor,
        new java.lang.String[] { "Demand", "ID", "NameSurname", "StartDate", "LastAccessed", "Interests", "IsOnline", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
